[package]
name = "maudio"
version = "0.1.0"
license = "MIT"
edition = "2024"
categories = ["multimedia::audio", "multimedia"]

[features]
device-tests = [] # used to hide tests in the github CI

[dependencies]
maudio-sys = { path = "../maudio-sys"}