[package]
name = "maudio"
version = "0.1.0"
license = "MIT"
edition = "2024"
categories = ["multimedia::audio", "multimedia"]

[features]
ci-tests = [] # disable the backend for the github CI

[dependencies]
maudio-sys = { path = "../maudio-sys"}